### PR TITLE
Actualizing the credentials creation on README.md

### PR DESCRIPTION
**Pull request by separovichabel**
I've found this change in simple-oauth2 and i fixed it doing this change.

### CODE REVIEW

**Comment by jasonjoh** [comment]
Interesting. What version of simple-oauth2 do you have? Just trying to figure out why this worked for me.

**Comment by separovichabel** [comment]
The version of simple-oauth2 is 1.5.2.
I think that the [simple-oauth2](https://www.npmjs.com/package/simple-oauth2) was upgraded and this change was made.
By the way our [authHelper.js](https://github.com/jasonjoh/node-tutorial/blob/outlook-api/authHelper.js) has the same code.
Thanks.

**Comment by jasonjoh** [comment]
Oh, my mistake :). I just realized this was the README, not the code. Thanks for fixing this!

**Comment by separovichabel** [comment]
Your welcome!

**Pull request merged**
